// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrulbroxyohykmffcwgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpydWxicm94eW9oeWttZmZjd2diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4OTM4NjMsImV4cCI6MjA2MzQ2OTg2M30.uNGrRPZlT0QQV-Nuvmttgj3Z8Qd5bx_Ey_CorYdWBjw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);